import React, { useState } from 'react';
import { motion } from 'framer-motion';
import SafeIcon from '../common/SafeIcon';
import * as FiIcons from 'react-icons/fi';

const { FiCopy, FiRefreshCw, FiPlay, FiCheck, FiStar } = FiIcons;

const AssignmentResult = ({ assignment, onReset }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(assignment);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>MPN Assignment</title>
          <style>
            body { 
              font-family: Arial, sans-serif; 
              padding: 40px; 
              line-height: 1.6;
              color: #333;
            }
            .header { 
              text-align: center; 
              margin-bottom: 40px; 
              border-bottom: 2px solid #8b5cf6;
              padding-bottom: 20px;
            }
            .assignment { 
              background: #f8fafc; 
              padding: 30px; 
              border-radius: 10px; 
              border-left: 5px solid #8b5cf6;
              font-size: 18px;
              margin: 20px 0;
            }
            .footer {
              text-align: center;
              margin-top: 40px;
              color: #666;
              font-size: 14px;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Music Production Ninja</h1>
            <h2>Personal Assignment</h2>
          </div>
          <div class="assignment">
            ${assignment}
          </div>
          <div class="footer">
            <p>Generated by MPN Assignment Generator</p>
            <p>Date: ${new Date().toLocaleDateString()}</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.5 }}
      className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20"
    >
      {/* Success Header */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="text-center mb-8"
      >
        <div className="inline-flex items-center justify-center w-20 h-20 bg-green-500/20 rounded-full mb-4">
          <SafeIcon icon={FiStar} className="w-10 h-10 text-green-300" />
        </div>
        <h2 className="text-3xl font-bold text-white mb-2">
          Your Quest Awaits!
        </h2>
        <p className="text-purple-200">
          Here's your personalized music production assignment
        </p>
      </motion.div>

      {/* Assignment Display */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
        className="bg-gradient-to-r from-purple-500/20 to-pink-500/20 rounded-xl p-6 mb-8 border border-purple-400/30"
      >
        <div className="text-white text-lg leading-relaxed">
          {assignment}
        </div>
      </motion.div>

      {/* Action Buttons */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.6 }}
        className="flex flex-wrap justify-center gap-4"
      >
        {/* Copy Assignment Button */}
        <motion.button
          onClick={handleCopy}
          className={`
            inline-flex items-center space-x-2 px-6 py-3 rounded-full font-medium transition-all duration-200
            ${copied
              ? 'bg-green-600 text-white'
              : 'bg-purple-600 hover:bg-purple-700 text-white'
            } shadow-lg hover:shadow-xl
          `}
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          <SafeIcon 
            icon={copied ? FiCheck : FiCopy} 
            className="w-5 h-5" 
          />
          <span>{copied ? 'Copied!' : 'Copy Assignment'}</span>
        </motion.button>

        {/* Start Assignment Button */}
        <motion.button
          onClick={handlePrint}
          className="inline-flex items-center space-x-2 px-6 py-3 rounded-full font-medium bg-green-600 hover:bg-green-700 text-white shadow-lg hover:shadow-xl transition-all duration-200"
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          <SafeIcon icon={FiPlay} className="w-5 h-5" />
          <span>Start Assignment</span>
        </motion.button>

        {/* Generate New Button */}
        <motion.button
          onClick={onReset}
          className="inline-flex items-center space-x-2 px-6 py-3 rounded-full font-medium bg-white/10 hover:bg-white/20 text-white border border-white/20 transition-all duration-200"
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          <SafeIcon icon={FiRefreshCw} className="w-5 h-5" />
          <span>Generate New</span>
        </motion.button>
      </motion.div>

      {/* Tips */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.8 }}
        className="mt-8 p-4 bg-blue-500/10 rounded-lg border border-blue-400/30"
      >
        <h3 className="text-blue-300 font-medium mb-2">💡 Pro Tips:</h3>
        <ul className="text-blue-200 text-sm space-y-1">
          <li>• Take your time with each step - quality over speed</li>
          <li>• Experiment with different sounds and techniques</li>
          <li>• Don't be afraid to add your own creative twist</li>
          <li>• Share your creation with the MPN community!</li>
        </ul>
      </motion.div>
    </motion.div>
  );
};

export default AssignmentResult;